import { Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import ItemCard from "../components/ItemCard/ItemCard";
import rustData from "../data/rust";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading>Sup</Heading>
      {rustData.map((item, index) => (
        <ItemCard key={index} {...item} />
      ))}
    </div>
  );
};

export default Home;
